### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by Yql66** [shinianj/zhenxun_plugin_DouyinShare#11]
01-08 18:21:07 [ERROR] nonebot | Failed to import "zhenxun_plugin_DouyinShare"
Traceback (most recent call last):
File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\bot.py", line 15, in
nonebot.load_plugins("extensive_plugin")
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 39
, in load_plugins
return manager.load_all_plugins()
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
172, in load_all_plugins
return set(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
173, in
filter(None, (self.load_plugin(name) for name in self.available_plugins))

File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
148, in load_plugin
module = importlib.import_module(
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib_init_.py", line 127, in import_mo
dule
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 986, in _find_and_load_unlocked
File "", line 680, in _load_unlocked
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line
237, in exec_module
super().exec_module(module)
File "", line 846, in exec_module
File "", line 983, in get_code
File "", line 913, in source_to_code
File "", line 228, in call_with_frames_removed
File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\extensive_plugin\zhenxun_plugin_DouyinShare_init.py", lin
e 106
if res.['code'] != 201:
^
SyntaxError: invalid syntax

**Comment by shinianj** [comment]
已修复，很是抱歉

**Comment by Yql66** [comment]
现在插件可以加载，但是机器人直接回复  网络不佳，抖音分享出错

**Comment by shinianj** [comment]
api问题，我也不好解决
